#!/bin/bash
#if 0; then
#EFI machine

loadkeys sv-latin1

#check ip & connection
ip a
ping -c 5 google.com

timedatectl set-ntp true

pacman -Syyy
pacman -S reflector --noconfirm
reflector -c Sweden -a 6 --sort rate --save /etc/pacman.d/mirrorlist
pacman -Syyy

lsblk
sleep 5
 
# to create the partitions programatically (rather than manually)
# we're going to simulate the manual input to fdisk
# The sed script strips off all the comments so that we can 
# document what we're doing in-line with the actual commands
# Note that a blank line (commented as "defualt" will send a empty
# line terminated with a newline to take the fdisk default.
sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | fdisk /dev/sda 
  g # create gpt partition table
  n # new partition
  1 # partition number 1
    # default - start at beginning of disk 
  +512M # boot parttion
  t # parttion type
  1 # efi partition
  n # new partition
  2 # partion number 2
    # default, start immidiately after preceding partition
    # default, use up rest of disk  
  p # print the in-memory partition table
  w # write the partition table
  q # and we're done
EOF

lsblk

mkfs.fat -F -F32 /dev/sda1
mkfs.ext4 -F /dev/sda2

mount /dev/sda2 /mnt
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot

lsblk
read -n 1
exit 1

pacstrap /mnt base

genfstab -U -p /mnt >> /mnt/etc/fstab
cat /mnt/etc/fstab

arch-chroot /mnt
ping -c 5 google.com

#fi
pacman -Sy
pacman -S --noconfirm base-devel grub efibootmgr dosfstools openssh os-prober mtools \
  linux-headers linux-lts linux-lts-headers network-manager-applet \
  networkmanager wireless_tools wpa_supplicant dialog 
#nano /etc/locale.gen
#en_US.UTF8 ...
echo LANG=en_US.UTF-8 > etc/locale.conf
locale-gen

systemctl enable sshd
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB --recheck
grub-mkconfig -o /boot/grub/grup.cfg

#mkdir /boot/grub/locale ???
#cp /usr/share/locale/en\@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo

#grub-mkconfig -o /boot/grub/grub.cfg

fallocate -l 2G /swapfile
chmod 600 /swapfile
mkswap /swapfile
echo '/swapfile none swap sw 0 0' | tee -a /etc/fstab
cat /etc/fstab

exit 1
passwd 
umount -a

reboot
